[package]
name = "car"
version = "0.1.0"
authors = [ "Bucur David"]
edition = "2018"
publish = false

[lib]
path = "src/carinformations.rs"

[dependencies.elrond-wasm]
version = "0.30.0"

[dev-dependencies.elrond-wasm-debug]
version = "0.27.4"
